apiVersion: polyfea.github.io/v1alpha1
kind: MicroFrontend
metadata:
  name: xle-equiptrack-ufe
spec:
  frontendClass: md-shell # default obsiahnutý v základe polyfea md-shell
  service:
    name: xle-equiptrack-ufe # referencia na službu odkiaľ sa má načítať modul
  modulePath: build/equiptrack-ufe.esm.js # cesta v rámci služby kde sa modul nachádza