apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xle-equiptrack-ufe-content
spec:
  microFrontend: xle-equiptrack-ufe
  element: xle-equip-app
  attributes:
    - name: api-base
      value: /xle-api
    - name: base-path
      value: ./xle-equip/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?xle-equip(/.*)?$"