apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

labels:
- pairs:
    app.kubernetes.io/part-of: wac-hospital
    app.kubernetes.io/name: xle-equiptrack
    wac-fiit.github.io/project: xle-equiptrack
  includeSelectors: true
  includeTemplates: true

resources:
- ../../../apps/xle-equiptrack-ufe
- ../../../apps/xle-equiptrack-webapi


components:
- ../../../components/version-release